version: "3.8"

services:
  db:
    image: ankane/pgvector
    container_name: pgvector-db
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: image_db
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: