export const speciesOptions: Record<string, string[]> = {
  dog: [
    'アイリッシュ・ウルフハウンド',
    'アイリッシュ・セター',
    'アフガン・ハウンド',
    'アメリカン・コッカー・スパニエル',
    'アメリカン・スタッフォードシャー・テリア',
    'イングリッシュ・コッカー・スパニエル',
    'イングリッシュ・スプリンガー・スパニエル',
    'ウエストハイランド・ホワイト・テリア',
    'ウェルシュ・コーギー・ペンブローク',
    'エアデール・テリア',
    'オーストラリアン・シェパード',
    '甲斐犬',
    'キャバリア・キング・チャールズ・スパニエル',
    'グレート・ピレニーズ',
    'キースホンド',
    'ケアーン・テリア',
    'ゴールデン・レトリーバー',
    'サルーキー',
    'シー・ズー',
    'シェットランド・シープドッグ',
    '柴犬',
    'シベリアン・ハスキー',
    'ジャック・ラッセル・テリア',
    'スコティッシュ・テリア',
    'セント・バーナード',
    'ダックスフンド',
    'ダルメシアン',
    'チャイニーズ・クレステッド・ドッグ',
    'チワワ',
    'ドゴ・アルヘンティーノ',
    'ドーベルマン',
    '日本スピッツ',
    'バーニーズ・マウンテン・ドッグ',
    'パグ',
    'バセット・ハウンド',
    'パピヨン',
    'ビアデッド・コリー',
    'ビーグル',
    'ビション・フリーゼ',
    'ブービエ・デ・フランダース',
    'フラットコーテッド・レトリーバー',
    'ブル・テリア',
    'ブルドッグ',
    'フレンチ・ブルドッグ',
    'ペキニーズ',
    'ベドリントン・テリア',
    'ベルジアン・タービュレン',
    'ボーダー・コリー',
    'ボクサー',
    'ボストン・テリア',
    'ポメラニアン',
    'ボルゾイ',
    'マルチーズ',
    'ミニチュア・シュナウザー',
    'ミニチュア・ピンシャー',
    'ヨークシャー・テリア',
    'ラフ・コリー',
    'ラブラドール・レトリーバー',
    'ロットワイラー',
    'ワイマラナー',
  ],
  cat: [
    'アメリカン・カール',
    'アメリカン・ショートヘアー',
    'エジプシャン・マウ',
    'コーニッシュ・レックス',
    'ジャパニーズ・ボブテイル',
    'シャム',
    'シンガプーラ',
    'スコティッシュ・フォールド',
    'ソマリ',
    'ターキッシュ・アンゴラ',
    'トンキニーズ',
    'ノルウェイジャン・フォレスト・キャット',
    'バーミラ',
    'ブリティッシュ・ショートヘア',
    'ハウスホールド・ペット',
    'ペルシャ',
    'ベンガル',
    'マンチカン',
    'メイン・クーン',
    'ラグドール',
    'ロシアン・ブルー',
  ],
};

export const speciesMap: Record<string, Record<string, string>> = {
  dog: {
    'アイリッシュ・ウルフハウンド': 'irish_wolfhound',
    'アイリッシュ・セター': 'irish_setter',
    'アフガン・ハウンド': 'afghan_hound',
    'アメリカン・コッカー・スパニエル': 'american_cocker_spaniel',
    'アメリカン・スタッフォードシャー・テリア':
      'american_staffordshire_terrier',
    'イングリッシュ・コッカー・スパニエル': 'english_cocker_spaniel',
    'イングリッシュ・スプリンガー・スパニエル': 'english_springer_spaniel',
    'ウエストハイランド・ホワイト・テリア': 'west_highland_white_terrier',
    'ウェルシュ・コーギー・ペンブローク': 'welsh_corgi_pembroke',
    'エアデール・テリア': 'airedale_terrier',
    'オーストラリアン・シェパード': 'australian_shepherd',
    甲斐犬: 'kai_ken',
    'キャバリア・キング・チャールズ・スパニエル':
      'cavalier_king_charles_spaniel',
    'グレート・ピレニーズ': 'great_pyrenees',
    キースホンド: 'keeshond',
    'ケアーン・テリア': 'cairn_terrier',
    'ゴールデン・レトリーバー': 'golden_retriever',
    サルーキー: 'saluki',
    'シー・ズー': 'shih_tzu',
    'シェットランド・シープドッグ': 'shetland_sheepdog',
    柴犬: 'shiba_inu',
    'シベリアン・ハスキー': 'siberian_husky',
    'ジャック・ラッセル・テリア': 'jack_russell_terrier',
    'スコティッシュ・テリア': 'scottish_terrier',
    'セント・バーナード': 'st_bernard',
    ダックスフンド: 'dachshund',
    ダルメシアン: 'dalmatian',
    'チャイニーズ・クレステッド・ドッグ': 'chinese_crested_dog',
    チワワ: 'chihuahua',
    'ドゴ・アルヘンティーノ': 'dogo_argentino',
    ドーベルマン: 'doberman',
    日本スピッツ: 'japanese_spitz',
    'バーニーズ・マウンテン・ドッグ': 'bernese_mountain_dog',
    パグ: 'pug',
    'バセット・ハウンド': 'basset_hound',
    パピヨン: 'papillon',
    'ビアデッド・コリー': 'bearded_collie',
    ビーグル: 'beagle',
    'ビション・フリーゼ': 'bichon_frise',
    'ブービエ・デ・フランダース': 'bouvier_des_flandres',
    'フラットコーテッド・レトリーバー': 'flat_coated_retriever',
    'ブル・テリア': 'bull_terrier',
    ブルドッグ: 'bulldog',
    'フレンチ・ブルドッグ': 'french_bulldog',
    ペキニーズ: 'pekinese',
    'ベドリントン・テリア': 'bedlington_terrier',
    'ベルジアン・タービュレン': 'belgian_tervuren',
    'ボーダー・コリー': 'border_collie',
    ボクサー: 'boxer',
    'ボストン・テリア': 'boston_terrier',
    ポメラニアン: 'pomeranian',
    ボルゾイ: 'borzoi',
    マルチーズ: 'maltese',
    'ミニチュア・シュナウザー': 'miniature_schnauzer',
    'ミニチュア・ピンシャー': 'miniature_pincher',
    'ヨークシャー・テリア': 'yorkshire_terrier',
    'ラフ・コリー': 'rough_collie',
    'ラブラドール・レトリーバー': 'labrador_retriever',
    ロットワイラー: 'rottweiler',
    ワイマラナー: 'weimaraner',
  },
  cat: {
    'アメリカン・カール': 'american_curl',
    'アメリカン・ショートヘアー': 'american_shorthair',
    'エジプシャン・マウ': 'egyptian_mau',
    'コーニッシュ・レックス': 'cornish_rex',
    'ジャパニーズ・ボブテイル': 'japanese_bobtail',
    シャム: 'siamese',
    シンガプーラ: 'singapura',
    'スコティッシュ・フォールド': 'scottish_fold',
    ソマリ: 'somali',
    'ターキッシュ・アンゴラ': 'turkish_angora',
    トンキニーズ: 'tonkinese',
    'ノルウェイジャン・フォレスト・キャット': 'norwegian_forest_cat',
    バーミラ: 'burmilla',
    'ブリティッシュ・ショートヘア': 'british_shorthair',
    'ハウスホールド・ペット': 'household_pet',
    ペルシャ: 'persian',
    ベンガル: 'bengal',
    マンチカン: 'munchkin',
    'メイン・クーン': 'maine_coon',
    ラグドール: 'ragdoll',
    'ロシアン・ブルー': 'russian_blue',
  },
};

export const reverseSpeciesMap: Record<string, Record<string, string>> = {
  dog: {},
  cat: {},
};

for (const petType in speciesMap) {
  reverseSpeciesMap[petType] = {};
  for (const jp in speciesMap[petType]) {
    const eng = speciesMap[petType][jp];
    reverseSpeciesMap[petType][eng] = jp;
  }
}
