// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Comment is the predicate function for comment builders.
type Comment func(*sql.Selector)

// DailyTask is the predicate function for dailytask builders.
type DailyTask func(*sql.Selector)

// FollowRelation is the predicate function for followrelation builders.
type FollowRelation func(*sql.Selector)

// Like is the predicate function for like builders.
type Like func(*sql.Selector)

// Pet is the predicate function for pet builders.
type Pet func(*sql.Selector)

// Post is the predicate function for post builders.
type Post func(*sql.Selector)

// TaskType is the predicate function for tasktype builders.
type TaskType func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
