// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/aki-13627/animalia/backend-go/ent/followrelation"
	"github.com/aki-13627/animalia/backend-go/ent/predicate"
	"github.com/aki-13627/animalia/backend-go/ent/user"
	"github.com/google/uuid"
)

// FollowRelationQuery is the builder for querying FollowRelation entities.
type FollowRelationQuery struct {
	config
	ctx        *QueryContext
	order      []followrelation.OrderOption
	inters     []Interceptor
	predicates []predicate.FollowRelation
	withFrom   *UserQuery
	withTo     *UserQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the FollowRelationQuery builder.
func (frq *FollowRelationQuery) Where(ps ...predicate.FollowRelation) *FollowRelationQuery {
	frq.predicates = append(frq.predicates, ps...)
	return frq
}

// Limit the number of records to be returned by this query.
func (frq *FollowRelationQuery) Limit(limit int) *FollowRelationQuery {
	frq.ctx.Limit = &limit
	return frq
}

// Offset to start from.
func (frq *FollowRelationQuery) Offset(offset int) *FollowRelationQuery {
	frq.ctx.Offset = &offset
	return frq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (frq *FollowRelationQuery) Unique(unique bool) *FollowRelationQuery {
	frq.ctx.Unique = &unique
	return frq
}

// Order specifies how the records should be ordered.
func (frq *FollowRelationQuery) Order(o ...followrelation.OrderOption) *FollowRelationQuery {
	frq.order = append(frq.order, o...)
	return frq
}

// QueryFrom chains the current query on the "from" edge.
func (frq *FollowRelationQuery) QueryFrom() *UserQuery {
	query := (&UserClient{config: frq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := frq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := frq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(followrelation.Table, followrelation.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, followrelation.FromTable, followrelation.FromColumn),
		)
		fromU = sqlgraph.SetNeighbors(frq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTo chains the current query on the "to" edge.
func (frq *FollowRelationQuery) QueryTo() *UserQuery {
	query := (&UserClient{config: frq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := frq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := frq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(followrelation.Table, followrelation.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, followrelation.ToTable, followrelation.ToColumn),
		)
		fromU = sqlgraph.SetNeighbors(frq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first FollowRelation entity from the query.
// Returns a *NotFoundError when no FollowRelation was found.
func (frq *FollowRelationQuery) First(ctx context.Context) (*FollowRelation, error) {
	nodes, err := frq.Limit(1).All(setContextOp(ctx, frq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{followrelation.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (frq *FollowRelationQuery) FirstX(ctx context.Context) *FollowRelation {
	node, err := frq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first FollowRelation ID from the query.
// Returns a *NotFoundError when no FollowRelation ID was found.
func (frq *FollowRelationQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = frq.Limit(1).IDs(setContextOp(ctx, frq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{followrelation.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (frq *FollowRelationQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := frq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single FollowRelation entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one FollowRelation entity is found.
// Returns a *NotFoundError when no FollowRelation entities are found.
func (frq *FollowRelationQuery) Only(ctx context.Context) (*FollowRelation, error) {
	nodes, err := frq.Limit(2).All(setContextOp(ctx, frq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{followrelation.Label}
	default:
		return nil, &NotSingularError{followrelation.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (frq *FollowRelationQuery) OnlyX(ctx context.Context) *FollowRelation {
	node, err := frq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only FollowRelation ID in the query.
// Returns a *NotSingularError when more than one FollowRelation ID is found.
// Returns a *NotFoundError when no entities are found.
func (frq *FollowRelationQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = frq.Limit(2).IDs(setContextOp(ctx, frq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{followrelation.Label}
	default:
		err = &NotSingularError{followrelation.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (frq *FollowRelationQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := frq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of FollowRelations.
func (frq *FollowRelationQuery) All(ctx context.Context) ([]*FollowRelation, error) {
	ctx = setContextOp(ctx, frq.ctx, ent.OpQueryAll)
	if err := frq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*FollowRelation, *FollowRelationQuery]()
	return withInterceptors[[]*FollowRelation](ctx, frq, qr, frq.inters)
}

// AllX is like All, but panics if an error occurs.
func (frq *FollowRelationQuery) AllX(ctx context.Context) []*FollowRelation {
	nodes, err := frq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of FollowRelation IDs.
func (frq *FollowRelationQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if frq.ctx.Unique == nil && frq.path != nil {
		frq.Unique(true)
	}
	ctx = setContextOp(ctx, frq.ctx, ent.OpQueryIDs)
	if err = frq.Select(followrelation.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (frq *FollowRelationQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := frq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (frq *FollowRelationQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, frq.ctx, ent.OpQueryCount)
	if err := frq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, frq, querierCount[*FollowRelationQuery](), frq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (frq *FollowRelationQuery) CountX(ctx context.Context) int {
	count, err := frq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (frq *FollowRelationQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, frq.ctx, ent.OpQueryExist)
	switch _, err := frq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (frq *FollowRelationQuery) ExistX(ctx context.Context) bool {
	exist, err := frq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the FollowRelationQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (frq *FollowRelationQuery) Clone() *FollowRelationQuery {
	if frq == nil {
		return nil
	}
	return &FollowRelationQuery{
		config:     frq.config,
		ctx:        frq.ctx.Clone(),
		order:      append([]followrelation.OrderOption{}, frq.order...),
		inters:     append([]Interceptor{}, frq.inters...),
		predicates: append([]predicate.FollowRelation{}, frq.predicates...),
		withFrom:   frq.withFrom.Clone(),
		withTo:     frq.withTo.Clone(),
		// clone intermediate query.
		sql:  frq.sql.Clone(),
		path: frq.path,
	}
}

// WithFrom tells the query-builder to eager-load the nodes that are connected to
// the "from" edge. The optional arguments are used to configure the query builder of the edge.
func (frq *FollowRelationQuery) WithFrom(opts ...func(*UserQuery)) *FollowRelationQuery {
	query := (&UserClient{config: frq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	frq.withFrom = query
	return frq
}

// WithTo tells the query-builder to eager-load the nodes that are connected to
// the "to" edge. The optional arguments are used to configure the query builder of the edge.
func (frq *FollowRelationQuery) WithTo(opts ...func(*UserQuery)) *FollowRelationQuery {
	query := (&UserClient{config: frq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	frq.withTo = query
	return frq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.FollowRelation.Query().
//		GroupBy(followrelation.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (frq *FollowRelationQuery) GroupBy(field string, fields ...string) *FollowRelationGroupBy {
	frq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &FollowRelationGroupBy{build: frq}
	grbuild.flds = &frq.ctx.Fields
	grbuild.label = followrelation.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.FollowRelation.Query().
//		Select(followrelation.FieldCreatedAt).
//		Scan(ctx, &v)
func (frq *FollowRelationQuery) Select(fields ...string) *FollowRelationSelect {
	frq.ctx.Fields = append(frq.ctx.Fields, fields...)
	sbuild := &FollowRelationSelect{FollowRelationQuery: frq}
	sbuild.label = followrelation.Label
	sbuild.flds, sbuild.scan = &frq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a FollowRelationSelect configured with the given aggregations.
func (frq *FollowRelationQuery) Aggregate(fns ...AggregateFunc) *FollowRelationSelect {
	return frq.Select().Aggregate(fns...)
}

func (frq *FollowRelationQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range frq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, frq); err != nil {
				return err
			}
		}
	}
	for _, f := range frq.ctx.Fields {
		if !followrelation.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if frq.path != nil {
		prev, err := frq.path(ctx)
		if err != nil {
			return err
		}
		frq.sql = prev
	}
	return nil
}

func (frq *FollowRelationQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*FollowRelation, error) {
	var (
		nodes       = []*FollowRelation{}
		withFKs     = frq.withFKs
		_spec       = frq.querySpec()
		loadedTypes = [2]bool{
			frq.withFrom != nil,
			frq.withTo != nil,
		}
	)
	if frq.withFrom != nil || frq.withTo != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, followrelation.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*FollowRelation).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &FollowRelation{config: frq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, frq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := frq.withFrom; query != nil {
		if err := frq.loadFrom(ctx, query, nodes, nil,
			func(n *FollowRelation, e *User) { n.Edges.From = e }); err != nil {
			return nil, err
		}
	}
	if query := frq.withTo; query != nil {
		if err := frq.loadTo(ctx, query, nodes, nil,
			func(n *FollowRelation, e *User) { n.Edges.To = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (frq *FollowRelationQuery) loadFrom(ctx context.Context, query *UserQuery, nodes []*FollowRelation, init func(*FollowRelation), assign func(*FollowRelation, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*FollowRelation)
	for i := range nodes {
		if nodes[i].user_following == nil {
			continue
		}
		fk := *nodes[i].user_following
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_following" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (frq *FollowRelationQuery) loadTo(ctx context.Context, query *UserQuery, nodes []*FollowRelation, init func(*FollowRelation), assign func(*FollowRelation, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*FollowRelation)
	for i := range nodes {
		if nodes[i].user_followers == nil {
			continue
		}
		fk := *nodes[i].user_followers
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_followers" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (frq *FollowRelationQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := frq.querySpec()
	_spec.Node.Columns = frq.ctx.Fields
	if len(frq.ctx.Fields) > 0 {
		_spec.Unique = frq.ctx.Unique != nil && *frq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, frq.driver, _spec)
}

func (frq *FollowRelationQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(followrelation.Table, followrelation.Columns, sqlgraph.NewFieldSpec(followrelation.FieldID, field.TypeUUID))
	_spec.From = frq.sql
	if unique := frq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if frq.path != nil {
		_spec.Unique = true
	}
	if fields := frq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, followrelation.FieldID)
		for i := range fields {
			if fields[i] != followrelation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := frq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := frq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := frq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := frq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (frq *FollowRelationQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(frq.driver.Dialect())
	t1 := builder.Table(followrelation.Table)
	columns := frq.ctx.Fields
	if len(columns) == 0 {
		columns = followrelation.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if frq.sql != nil {
		selector = frq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if frq.ctx.Unique != nil && *frq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range frq.predicates {
		p(selector)
	}
	for _, p := range frq.order {
		p(selector)
	}
	if offset := frq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := frq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// FollowRelationGroupBy is the group-by builder for FollowRelation entities.
type FollowRelationGroupBy struct {
	selector
	build *FollowRelationQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (frgb *FollowRelationGroupBy) Aggregate(fns ...AggregateFunc) *FollowRelationGroupBy {
	frgb.fns = append(frgb.fns, fns...)
	return frgb
}

// Scan applies the selector query and scans the result into the given value.
func (frgb *FollowRelationGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, frgb.build.ctx, ent.OpQueryGroupBy)
	if err := frgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FollowRelationQuery, *FollowRelationGroupBy](ctx, frgb.build, frgb, frgb.build.inters, v)
}

func (frgb *FollowRelationGroupBy) sqlScan(ctx context.Context, root *FollowRelationQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(frgb.fns))
	for _, fn := range frgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*frgb.flds)+len(frgb.fns))
		for _, f := range *frgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*frgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := frgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// FollowRelationSelect is the builder for selecting fields of FollowRelation entities.
type FollowRelationSelect struct {
	*FollowRelationQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (frs *FollowRelationSelect) Aggregate(fns ...AggregateFunc) *FollowRelationSelect {
	frs.fns = append(frs.fns, fns...)
	return frs
}

// Scan applies the selector query and scans the result into the given value.
func (frs *FollowRelationSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, frs.ctx, ent.OpQuerySelect)
	if err := frs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FollowRelationQuery, *FollowRelationSelect](ctx, frs.FollowRelationQuery, frs, frs.inters, v)
}

func (frs *FollowRelationSelect) sqlScan(ctx context.Context, root *FollowRelationQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(frs.fns))
	for _, fn := range frs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*frs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := frs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
