// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/aki-13627/animalia/backend-go/ent/predicate"
	"github.com/aki-13627/animalia/backend-go/ent/tasktype"
)

// TaskTypeQuery is the builder for querying TaskType entities.
type TaskTypeQuery struct {
	config
	ctx        *QueryContext
	order      []tasktype.OrderOption
	inters     []Interceptor
	predicates []predicate.TaskType
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TaskTypeQuery builder.
func (ttq *TaskTypeQuery) Where(ps ...predicate.TaskType) *TaskTypeQuery {
	ttq.predicates = append(ttq.predicates, ps...)
	return ttq
}

// Limit the number of records to be returned by this query.
func (ttq *TaskTypeQuery) Limit(limit int) *TaskTypeQuery {
	ttq.ctx.Limit = &limit
	return ttq
}

// Offset to start from.
func (ttq *TaskTypeQuery) Offset(offset int) *TaskTypeQuery {
	ttq.ctx.Offset = &offset
	return ttq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ttq *TaskTypeQuery) Unique(unique bool) *TaskTypeQuery {
	ttq.ctx.Unique = &unique
	return ttq
}

// Order specifies how the records should be ordered.
func (ttq *TaskTypeQuery) Order(o ...tasktype.OrderOption) *TaskTypeQuery {
	ttq.order = append(ttq.order, o...)
	return ttq
}

// First returns the first TaskType entity from the query.
// Returns a *NotFoundError when no TaskType was found.
func (ttq *TaskTypeQuery) First(ctx context.Context) (*TaskType, error) {
	nodes, err := ttq.Limit(1).All(setContextOp(ctx, ttq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{tasktype.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ttq *TaskTypeQuery) FirstX(ctx context.Context) *TaskType {
	node, err := ttq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TaskType ID from the query.
// Returns a *NotFoundError when no TaskType ID was found.
func (ttq *TaskTypeQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ttq.Limit(1).IDs(setContextOp(ctx, ttq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{tasktype.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ttq *TaskTypeQuery) FirstIDX(ctx context.Context) int {
	id, err := ttq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TaskType entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TaskType entity is found.
// Returns a *NotFoundError when no TaskType entities are found.
func (ttq *TaskTypeQuery) Only(ctx context.Context) (*TaskType, error) {
	nodes, err := ttq.Limit(2).All(setContextOp(ctx, ttq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{tasktype.Label}
	default:
		return nil, &NotSingularError{tasktype.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ttq *TaskTypeQuery) OnlyX(ctx context.Context) *TaskType {
	node, err := ttq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TaskType ID in the query.
// Returns a *NotSingularError when more than one TaskType ID is found.
// Returns a *NotFoundError when no entities are found.
func (ttq *TaskTypeQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ttq.Limit(2).IDs(setContextOp(ctx, ttq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{tasktype.Label}
	default:
		err = &NotSingularError{tasktype.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ttq *TaskTypeQuery) OnlyIDX(ctx context.Context) int {
	id, err := ttq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TaskTypes.
func (ttq *TaskTypeQuery) All(ctx context.Context) ([]*TaskType, error) {
	ctx = setContextOp(ctx, ttq.ctx, ent.OpQueryAll)
	if err := ttq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TaskType, *TaskTypeQuery]()
	return withInterceptors[[]*TaskType](ctx, ttq, qr, ttq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ttq *TaskTypeQuery) AllX(ctx context.Context) []*TaskType {
	nodes, err := ttq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TaskType IDs.
func (ttq *TaskTypeQuery) IDs(ctx context.Context) (ids []int, err error) {
	if ttq.ctx.Unique == nil && ttq.path != nil {
		ttq.Unique(true)
	}
	ctx = setContextOp(ctx, ttq.ctx, ent.OpQueryIDs)
	if err = ttq.Select(tasktype.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ttq *TaskTypeQuery) IDsX(ctx context.Context) []int {
	ids, err := ttq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ttq *TaskTypeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ttq.ctx, ent.OpQueryCount)
	if err := ttq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ttq, querierCount[*TaskTypeQuery](), ttq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ttq *TaskTypeQuery) CountX(ctx context.Context) int {
	count, err := ttq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ttq *TaskTypeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ttq.ctx, ent.OpQueryExist)
	switch _, err := ttq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ttq *TaskTypeQuery) ExistX(ctx context.Context) bool {
	exist, err := ttq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TaskTypeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ttq *TaskTypeQuery) Clone() *TaskTypeQuery {
	if ttq == nil {
		return nil
	}
	return &TaskTypeQuery{
		config:     ttq.config,
		ctx:        ttq.ctx.Clone(),
		order:      append([]tasktype.OrderOption{}, ttq.order...),
		inters:     append([]Interceptor{}, ttq.inters...),
		predicates: append([]predicate.TaskType{}, ttq.predicates...),
		// clone intermediate query.
		sql:  ttq.sql.Clone(),
		path: ttq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Type enum.TaskType `json:"type,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TaskType.Query().
//		GroupBy(tasktype.FieldType).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ttq *TaskTypeQuery) GroupBy(field string, fields ...string) *TaskTypeGroupBy {
	ttq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TaskTypeGroupBy{build: ttq}
	grbuild.flds = &ttq.ctx.Fields
	grbuild.label = tasktype.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Type enum.TaskType `json:"type,omitempty"`
//	}
//
//	client.TaskType.Query().
//		Select(tasktype.FieldType).
//		Scan(ctx, &v)
func (ttq *TaskTypeQuery) Select(fields ...string) *TaskTypeSelect {
	ttq.ctx.Fields = append(ttq.ctx.Fields, fields...)
	sbuild := &TaskTypeSelect{TaskTypeQuery: ttq}
	sbuild.label = tasktype.Label
	sbuild.flds, sbuild.scan = &ttq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TaskTypeSelect configured with the given aggregations.
func (ttq *TaskTypeQuery) Aggregate(fns ...AggregateFunc) *TaskTypeSelect {
	return ttq.Select().Aggregate(fns...)
}

func (ttq *TaskTypeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ttq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ttq); err != nil {
				return err
			}
		}
	}
	for _, f := range ttq.ctx.Fields {
		if !tasktype.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ttq.path != nil {
		prev, err := ttq.path(ctx)
		if err != nil {
			return err
		}
		ttq.sql = prev
	}
	return nil
}

func (ttq *TaskTypeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TaskType, error) {
	var (
		nodes = []*TaskType{}
		_spec = ttq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TaskType).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TaskType{config: ttq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ttq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (ttq *TaskTypeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ttq.querySpec()
	_spec.Node.Columns = ttq.ctx.Fields
	if len(ttq.ctx.Fields) > 0 {
		_spec.Unique = ttq.ctx.Unique != nil && *ttq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ttq.driver, _spec)
}

func (ttq *TaskTypeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(tasktype.Table, tasktype.Columns, sqlgraph.NewFieldSpec(tasktype.FieldID, field.TypeInt))
	_spec.From = ttq.sql
	if unique := ttq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ttq.path != nil {
		_spec.Unique = true
	}
	if fields := ttq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tasktype.FieldID)
		for i := range fields {
			if fields[i] != tasktype.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ttq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ttq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ttq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ttq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ttq *TaskTypeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ttq.driver.Dialect())
	t1 := builder.Table(tasktype.Table)
	columns := ttq.ctx.Fields
	if len(columns) == 0 {
		columns = tasktype.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ttq.sql != nil {
		selector = ttq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ttq.ctx.Unique != nil && *ttq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ttq.predicates {
		p(selector)
	}
	for _, p := range ttq.order {
		p(selector)
	}
	if offset := ttq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ttq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TaskTypeGroupBy is the group-by builder for TaskType entities.
type TaskTypeGroupBy struct {
	selector
	build *TaskTypeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ttgb *TaskTypeGroupBy) Aggregate(fns ...AggregateFunc) *TaskTypeGroupBy {
	ttgb.fns = append(ttgb.fns, fns...)
	return ttgb
}

// Scan applies the selector query and scans the result into the given value.
func (ttgb *TaskTypeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ttgb.build.ctx, ent.OpQueryGroupBy)
	if err := ttgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TaskTypeQuery, *TaskTypeGroupBy](ctx, ttgb.build, ttgb, ttgb.build.inters, v)
}

func (ttgb *TaskTypeGroupBy) sqlScan(ctx context.Context, root *TaskTypeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ttgb.fns))
	for _, fn := range ttgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ttgb.flds)+len(ttgb.fns))
		for _, f := range *ttgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ttgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ttgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TaskTypeSelect is the builder for selecting fields of TaskType entities.
type TaskTypeSelect struct {
	*TaskTypeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tts *TaskTypeSelect) Aggregate(fns ...AggregateFunc) *TaskTypeSelect {
	tts.fns = append(tts.fns, fns...)
	return tts
}

// Scan applies the selector query and scans the result into the given value.
func (tts *TaskTypeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tts.ctx, ent.OpQuerySelect)
	if err := tts.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TaskTypeQuery, *TaskTypeSelect](ctx, tts.TaskTypeQuery, tts, tts.inters, v)
}

func (tts *TaskTypeSelect) sqlScan(ctx context.Context, root *TaskTypeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(tts.fns))
	for _, fn := range tts.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*tts.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
