// Code generated by ent, DO NOT EDIT.

package tasktype

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the tasktype type in the database.
	Label = "task_type"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldTextFeature holds the string denoting the text_feature field in the database.
	FieldTextFeature = "text_feature"
	// Table holds the table name of the tasktype in the database.
	Table = "task_types"
)

// Columns holds all SQL columns for tasktype fields.
var Columns = []string{
	FieldID,
	FieldType,
	FieldTextFeature,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the TaskType queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByTextFeature orders the results by the text_feature field.
func ByTextFeature(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTextFeature, opts...).ToFunc()
}
