// Code generated by ent, DO NOT EDIT.

package tasktype

import (
	"entgo.io/ent/dialect/sql"
	"github.com/aki-13627/animalia/backend-go/ent/enum"
	"github.com/aki-13627/animalia/backend-go/ent/predicate"
	pgvector "github.com/pgvector/pgvector-go"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.TaskType {
	return predicate.TaskType(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.TaskType {
	return predicate.TaskType(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.TaskType {
	return predicate.TaskType(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.TaskType {
	return predicate.TaskType(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.TaskType {
	return predicate.TaskType(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.TaskType {
	return predicate.TaskType(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.TaskType {
	return predicate.TaskType(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.TaskType {
	return predicate.TaskType(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.TaskType {
	return predicate.TaskType(sql.FieldLTE(FieldID, id))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v enum.TaskType) predicate.TaskType {
	vc := string(v)
	return predicate.TaskType(sql.FieldEQ(FieldType, vc))
}

// TextFeature applies equality check predicate on the "text_feature" field. It's identical to TextFeatureEQ.
func TextFeature(v pgvector.Vector) predicate.TaskType {
	return predicate.TaskType(sql.FieldEQ(FieldTextFeature, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v enum.TaskType) predicate.TaskType {
	vc := string(v)
	return predicate.TaskType(sql.FieldEQ(FieldType, vc))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v enum.TaskType) predicate.TaskType {
	vc := string(v)
	return predicate.TaskType(sql.FieldNEQ(FieldType, vc))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...enum.TaskType) predicate.TaskType {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.TaskType(sql.FieldIn(FieldType, v...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...enum.TaskType) predicate.TaskType {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.TaskType(sql.FieldNotIn(FieldType, v...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v enum.TaskType) predicate.TaskType {
	vc := string(v)
	return predicate.TaskType(sql.FieldGT(FieldType, vc))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v enum.TaskType) predicate.TaskType {
	vc := string(v)
	return predicate.TaskType(sql.FieldGTE(FieldType, vc))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v enum.TaskType) predicate.TaskType {
	vc := string(v)
	return predicate.TaskType(sql.FieldLT(FieldType, vc))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v enum.TaskType) predicate.TaskType {
	vc := string(v)
	return predicate.TaskType(sql.FieldLTE(FieldType, vc))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v enum.TaskType) predicate.TaskType {
	vc := string(v)
	return predicate.TaskType(sql.FieldContains(FieldType, vc))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v enum.TaskType) predicate.TaskType {
	vc := string(v)
	return predicate.TaskType(sql.FieldHasPrefix(FieldType, vc))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v enum.TaskType) predicate.TaskType {
	vc := string(v)
	return predicate.TaskType(sql.FieldHasSuffix(FieldType, vc))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v enum.TaskType) predicate.TaskType {
	vc := string(v)
	return predicate.TaskType(sql.FieldEqualFold(FieldType, vc))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v enum.TaskType) predicate.TaskType {
	vc := string(v)
	return predicate.TaskType(sql.FieldContainsFold(FieldType, vc))
}

// TextFeatureEQ applies the EQ predicate on the "text_feature" field.
func TextFeatureEQ(v pgvector.Vector) predicate.TaskType {
	return predicate.TaskType(sql.FieldEQ(FieldTextFeature, v))
}

// TextFeatureNEQ applies the NEQ predicate on the "text_feature" field.
func TextFeatureNEQ(v pgvector.Vector) predicate.TaskType {
	return predicate.TaskType(sql.FieldNEQ(FieldTextFeature, v))
}

// TextFeatureIn applies the In predicate on the "text_feature" field.
func TextFeatureIn(vs ...pgvector.Vector) predicate.TaskType {
	return predicate.TaskType(sql.FieldIn(FieldTextFeature, vs...))
}

// TextFeatureNotIn applies the NotIn predicate on the "text_feature" field.
func TextFeatureNotIn(vs ...pgvector.Vector) predicate.TaskType {
	return predicate.TaskType(sql.FieldNotIn(FieldTextFeature, vs...))
}

// TextFeatureGT applies the GT predicate on the "text_feature" field.
func TextFeatureGT(v pgvector.Vector) predicate.TaskType {
	return predicate.TaskType(sql.FieldGT(FieldTextFeature, v))
}

// TextFeatureGTE applies the GTE predicate on the "text_feature" field.
func TextFeatureGTE(v pgvector.Vector) predicate.TaskType {
	return predicate.TaskType(sql.FieldGTE(FieldTextFeature, v))
}

// TextFeatureLT applies the LT predicate on the "text_feature" field.
func TextFeatureLT(v pgvector.Vector) predicate.TaskType {
	return predicate.TaskType(sql.FieldLT(FieldTextFeature, v))
}

// TextFeatureLTE applies the LTE predicate on the "text_feature" field.
func TextFeatureLTE(v pgvector.Vector) predicate.TaskType {
	return predicate.TaskType(sql.FieldLTE(FieldTextFeature, v))
}

// TextFeatureIsNil applies the IsNil predicate on the "text_feature" field.
func TextFeatureIsNil() predicate.TaskType {
	return predicate.TaskType(sql.FieldIsNull(FieldTextFeature))
}

// TextFeatureNotNil applies the NotNil predicate on the "text_feature" field.
func TextFeatureNotNil() predicate.TaskType {
	return predicate.TaskType(sql.FieldNotNull(FieldTextFeature))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TaskType) predicate.TaskType {
	return predicate.TaskType(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TaskType) predicate.TaskType {
	return predicate.TaskType(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TaskType) predicate.TaskType {
	return predicate.TaskType(sql.NotPredicates(p))
}
