version: "3.8"

services:
  api:
    build:
      context: ./backend-go
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./.env:/app/.env
    environment:
      - SEED=${SEED}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # restart: always

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    restart: always

volumes:
  postgres_data:
