name: Frontend CI

on:
  push:
    paths:
      - "app-front/**"
  pull_request:
    paths:
      - "app-front/**"

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app-front

    steps:
      - name: ✅ Checkout repository
        uses: actions/checkout@v3

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🧪 Run tests
        run: npm test
